name: ttp_app
description: App to make a businessprocess a bit more convienient.
publish_to: 'none'
version: 0.6.1+66

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  packaging_module:
    path: ./packaging_module
  tool_planning:
    path: ./tool_planning
  hangerstations_dashboard_module:
    path: ./hangerstations_dashboard_module
  url_launcher: ^6.1.12
  flutter_launcher_icons: ^0.14.1
  qr_code_scanner: ^1.0.1
  vibration: ^2.0.1
  device_info_plus: ^10.1.2
  platform: ^3.1.1
  shared_preferences: ^2.2.0
  flutter_dropdown: ^1.0.1+hotfix.1
  webview_windows: ^0.4.0
  window_manager: ^0.4.3
  flutter_html: 3.0.0-beta.2
  http: ^1.1.0
  html: ^0.15.4
  dio: ^5.4.3+1
  video_player: ^2.9.2
  video_player_win: ^3.1.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  syncfusion_flutter_pdfviewer: ^27.1.53
  syncfusion_flutter_pdf: ^27.1.53
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.10+1
  path: ^1.9.0
  flutter_inappwebview: ^6.1.3
  intl: ^0.19.0
  data_table_2: ^2.5.15
  flutter_typeahead: ^4.8.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/leuchtturm.png
    - assets/ac.png
    - assets/images/ac.png
    - assets/bookstack.png
    - assets/leuchtturm_blue.png
    - assets/productionplan.png
    - assets/anbauteile.json
    - assets/wzabt_pdfs/
    - assets/IKOffice.ico
    - assets/extruder.svg
  
msix_config:
  display_name: ttp App
  publisher_display_name: ttp Papenburg GmbH
  identity_name: com.app.ttpurlcompleter
  msix_version: 1.0.1.1
  logo_path: assets\icon\AppIcon.png
  capabilities: internetClient, location, microphone, webcam