name: ttp_app
description: App to make a businessprocess a bit more convienient.
publish_to: 'none'
version: 0.4.1+28

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12
  flutter_launcher_icons: ^0.13.1
  qr_code_scanner: ^1.0.1
  vibration: ^1.8.4
  device_info_plus: ^9.1.1
  platform: ^3.1.1
  shared_preferences: ^2.2.0
  flutter_dropdown: ^1.0.1+hotfix.1
  pdfx: ^2.4.0
  flutter_typeahead: ^4.8.0
  flutter_webview_plugin: ^0.4.0
  webview_windows: ^0.3.0
  window_manager: ^0.3.7
  flutter_html: 3.0.0-beta.2
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/leuchtturm.png
    - assets/ac.png
    - assets/bookstack.png
    - assets/leuchtturm_blue.png
    - assets/productionplan.png
    - assets/anbauteile.json
    - assets/wzabt_pdfs/
    - assets/IKOffice.ico
  
msix_config:
  display_name: WIM Profilauswahl
  publisher_display_name: ttp Papenburg GmbH
  identity_name: com.app.ttpurlcompleter
  msix_version: 1.0.1.1
  logo_path: assets\icon\AppIcon.png
  capabilities: internetClient, location, microphone, webcam