name: ttp_urlcompleter
description: App to make a businessprocess a bit more convienient.
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12
  flutter_launcher_icons: "^0.13.1"
  qr_code_scanner: ^1.0.1
  vibration: ^1.8.1
  device_info_plus: ^9.0.3
  platform: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/leuchtturm.png
    - assets/ac.png
    - assets/bookstack.png
    - assets/leuchtturm_blue.png
  
msix_config:
  display_name: WIM Profilauswahl
  publisher_display_name: ttp Papenburg GmbH
  identity_name: com.app.ttpurlcompleter
  msix_version: 1.0.1.1
  logo_path: assets\icon\AppIcon.png
  capabilities: internetClient, location, microphone, webcam